backend:
  name: github # Refer to https://www.netlifycms.org/docs/authentication-backends/ for auth backend list and instructions
  branch: dev # Branch to update
  repo: thmsl/gatsby-adv # Repo for pushing new commits. Make sure to replace with your repo!

media_folder: static/assets/uploads
public_folder: assets

collections:
  - name: blog
    label: "Post"
    folder: "content/blog"
    path: "{{year}}/{{month}}/{{day}}/{{slug}}"
    permalink: "{{year}}/{{month}}/{{day}}/{{slug}}"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content type", name: "contenttype", widget: "hidden", default: "blog"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image", required: false }
      - { label: "Category", name: "category", widget: "list" }
      - { label: "Tags", name: "tag", widget: "list" }
      - { label: "Intro", name: "intro", widget: "string" }
      - { label: "Text", name: "text", widget: "markdown" }
  - name: solution
    label: "Solution"
    folder: "content/solutions"
    path: "{{slug}}"
    permalink: "{{slug}}"
    create: true
    slug: "{{title}}"
    fields:
      - { label: "Title", name: "title", widget: "string" }
      - { label: "Content type", name: "contenttype", widget: "hidden", default: "solution"}
      - { label: "Publish Date", name: "date", widget: "datetime" }
      - { label: "Cover Image", name: "cover", widget: "image" }
      - { label: "Intro 1", name: "intro1", widget: "markdown" }
      - { label: "Text 1", name: "text1", widget: "markdown" }      
      - { label: "Image 1", name: "image1", widget: "image" }      
      - { label: "Text 2", name: "text2", widget: "markdown" }      
      - { label: "Image 2", name: "image2", widget: "image" }      
      - { label: "Text 3", name: "text3", widget: "markdown" }      
      - { label: "Image 3", name: "image3", widget: "image" }
      - { label: "Intro 2", name: "intro2", widget: "markdown" }
      - { label: "Text 4", name: "text4", widget: "markdown" }      
      - { label: "Image 4", name: "image4", widget: "image" }      
      - { label: "Text 5", name: "text5", widget: "markdown" }      
      - { label: "Image 5", name: "image5", widget: "image" }            
      - { label: "Text 6", name: "text6", widget: "markdown" }      
      - { label: "Image 6", name: "image6", widget: "image" }   
      - { label: "Outro", name: "outro", widget: "markdown" }                  



